# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'Grapso' do
	project 'Grapso.xcodeproj'
	pod 'Firebase/Analytics', '~> 7.0.0'
    pod 'Firebase/RemoteConfig', '~> 7.0.0'
    pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
    pod 'razorpay-pod'
	pod 'Siren'
end
